Repository elastic/endpoint-package, pull requests merged in 2022-08, with the labels that each got.

#280 updated ECS version to 8.3 and added missing mappings to process inde…
  Makefile
  custom_subsets/elastic_endpoint/process/linux_event_model_event.yaml
  package/endpoint/data_stream/alerts/fields/fields.yml
  package/endpoint/data_stream/alerts/sample_event.json
  package/endpoint/data_stream/file/fields/fields.yml
  package/endpoint/data_stream/file/sample_event.json
  package/endpoint/data_stream/library/fields/fields.yml
  package/endpoint/data_stream/library/sample_event.json
  package/endpoint/data_stream/metadata/fields/fields.yml
  package/endpoint/data_stream/metadata/sample_event.json
  package/endpoint/data_stream/metrics/fields/fields.yml
  package/endpoint/data_stream/metrics/sample_event.json
  package/endpoint/data_stream/network/fields/fields.yml
  package/endpoint/data_stream/network/sample_event.json
  package/endpoint/data_stream/policy/fields/fields.yml
  package/endpoint/data_stream/policy/sample_event.json
  package/endpoint/data_stream/process/fields/fields.yml
  package/endpoint/data_stream/process/sample_event.json
  package/endpoint/data_stream/registry/fields/fields.yml
  package/endpoint/data_stream/registry/sample_event.json
  package/endpoint/data_stream/security/fields/fields.yml
  package/endpoint/data_stream/security/sample_event.json
  package/endpoint/docs/README.md
  schemas/v1/alerts/linux_event_model_event.yaml
  schemas/v1/alerts/malware_event.yaml
  schemas/v1/alerts/memory_protection_event.yaml
  schemas/v1/alerts/ransomware_event.yaml
  schemas/v1/alerts/rule_detection_event.yaml
  schemas/v1/file/file.yaml
  schemas/v1/file/unquarantine.yaml
  schemas/v1/library/library.yaml
  schemas/v1/metadata/metadata.yaml
  schemas/v1/metrics/metrics.yaml
  schemas/v1/network/network.yaml
  schemas/v1/policy/policy.yaml
  schemas/v1/process/linux_event_model_event.yaml
  schemas/v1/process/process.yaml
  schemas/v1/registry/registry.yaml
  schemas/v1/security/security.yaml
Labels: v8.4.1

#285 [backport][8.4] replace file.Ext.* with existing fields within alerts (#281)
  custom_subsets/elastic_endpoint/alerts/malware_event.yaml
  custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
  custom_subsets/elastic_endpoint/alerts/ransomware_event.yaml
  custom_subsets/elastic_endpoint/alerts/rule_detection_event.yaml
  package/endpoint/data_stream/alerts/fields/fields.yml
  package/endpoint/docs/README.md
  schemas/v1/alerts/malware_event.yaml
  schemas/v1/alerts/memory_protection_event.yaml
  schemas/v1/alerts/ransomware_event.yaml
  schemas/v1/alerts/rule_detection_event.yaml
Labels: backport

#286 add changelog for 8.4.1
  package/endpoint/changelog.yml
Labels: v8.4.1

#287 [backport][8.4] add changelog for 8.4.1 (#286)
  package/endpoint/changelog.yml
Labels: backport

#289 Bump kibana min for next cycle
  package/endpoint/manifest.yml
Labels: v8.5.0
