Repository elastic/endpoint-package, pull requests merged in 2022-09, with the labels that each got.

#295 add new `.fleet-agents` fields to united index
  package/endpoint/elasticsearch/index_template/metrics-metadata-united.json
Labels: v8.5.0

#294 [Terminal output] Fields coming in 8.5 added to custom_schemas/subsets
  custom_schemas/custom_process.yml
  custom_subsets/elastic_endpoint/process/linux_event_model_event.yaml
  package/endpoint/data_stream/alerts/fields/fields.yml
  package/endpoint/data_stream/process/fields/fields.yml
  package/endpoint/data_stream/process/sample_event.json
  package/endpoint/docs/README.md
  schemas/v1/alerts/linux_event_model_event.yaml
  schemas/v1/process/linux_event_model_event.yaml
Labels: v8.5.0

#292 Update integration name to Elastic Defend
  doc_templates/endpoint/docs/README.md
  package/endpoint/docs/README.md
  package/endpoint/manifest.yml
Labels: Team:Onboarding and Lifecycle Mgt

#296 jjbb: use fleet-ci
  .ci/jobs/defaults.yml
  .ci/jobs/endpoint-package-mbp.yml
  README.md
Labels: Team:Automation

#299 [8.5] attested_user and attested_groups added to process.entry_leader
  custom_schemas/custom_group.yml
  custom_schemas/custom_user.yml
  custom_subsets/elastic_endpoint/process/linux_event_model_event.yaml
  package/endpoint/data_stream/process/fields/fields.yml
  package/endpoint/data_stream/process/sample_event.json
  package/endpoint/docs/README.md
  schemas/v1/process/linux_event_model_event.yaml
Labels: v8.5.0
