Repository elastic/endpoint-package, pull requests merged in 2022-04, with the labels that each got.

#228 add code signature fields for macOS signatures
  custom_schemas/custom_dll.yml
  custom_schemas/custom_file.yml
  custom_schemas/custom_process.yml
  custom_subsets/elastic_endpoint/alerts/malware_event.yaml
  custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
  custom_subsets/elastic_endpoint/alerts/ransomware_event.yaml
  custom_subsets/elastic_endpoint/library/library.yaml
  package/endpoint/data_stream/alerts/fields/fields.yml
  package/endpoint/data_stream/library/fields/fields.yml
  package/endpoint/data_stream/process/fields/fields.yml
  package/endpoint/docs/README.md
  schemas/v1/alerts/malware_event.yaml
  schemas/v1/alerts/memory_protection_event.yaml
  schemas/v1/alerts/ransomware_event.yaml
  schemas/v1/library/library.yaml
Labels: Team:Onboarding and Lifecycle Mgt, schema, v8.0.0, v8.1.0

#244 improve documentation for adding fields to exceptions dropdown
  .github/PULL_REQUEST_TEMPLATE
  README.md
Labels: documentation

#253 Disable default Lint in make
  Makefile
Labels: Team:Onboarding and Lifecycle Mgt

#252 Generate catchup
  custom_subsets/elastic_endpoint/library/library.yaml
  generated/library/ecs/ecs_flat.yml
  generated/library/elasticsearch/7/template.json
  package/endpoint/data_stream/alerts/fields/fields.yml
  package/endpoint/data_stream/library/fields/fields.yml
  package/endpoint/data_stream/process/fields/fields.yml
  package/endpoint/docs/README.md
  schemas/v1/library/library.yaml
Labels: bug, Team:Onboarding and Lifecycle Mgt, schema, v8.3.0

#250 CI
  .ci/Jenkinsfile
  .ci/jobs/defaults.yml
  package/endpoint/data_stream/network/_dev/test/pipeline/test-common-config.yml
Labels: enhancement, Team:Onboarding and Lifecycle Mgt
