Repository elastic/endpoint-package, pull requests merged in 2024-08, with the labels that each got.

#525 Add Target.process.Ext.authentication_id and process.Ext.authentication_id to Security events
  custom_subsets/elastic_endpoint/security/security.yaml
  package/endpoint/data_stream/security/fields/fields.yml
  package/endpoint/data_stream/security/sample_event.json
  package/endpoint/docs/README.md
  schemas/v1/security/security.yaml
Labels: v8.16.0

#528 Add process.Ext.protection to Windows library events
  custom_documentation/doc/endpoint/library/windows/windows_library_load.md
  custom_documentation/src/endpoint/data_stream/library/windows/windows_library_load.yaml
  custom_subsets/elastic_endpoint/library/library.yaml
  package/endpoint/data_stream/library/fields/fields.yml
  package/endpoint/data_stream/library/sample_event.json
  package/endpoint/data_stream/process/sample_event.json
  package/endpoint/docs/README.md
  schemas/v1/library/library.yaml
Labels: v8.15.1

#529 [backport] Add process.Ext.protection to Windows library events (#528)
  custom_documentation/doc/endpoint/library/windows/windows_library_load.md
  custom_documentation/src/endpoint/data_stream/library/windows/windows_library_load.yaml
  custom_subsets/elastic_endpoint/library/library.yaml
  package/endpoint/data_stream/library/fields/fields.yml
  package/endpoint/data_stream/library/sample_event.json
  package/endpoint/data_stream/process/sample_event.json
  package/endpoint/docs/README.md
  schemas/v1/library/library.yaml
Labels: backport

#534 update custom documentation
  custom_documentation/src/endpoint/data_stream/alerts/windows/windows_malware_alert.yaml
  custom_documentation/src/endpoint/data_stream/security/windows/windows_security_log_off.yaml
  custom_documentation/src/endpoint/data_stream/security/windows/windows_security_log_on.yaml
Labels: v8.16.0
