Repository elastic/endpoint-package, pull requests merged in 2024-09, with the labels that each got.

#535 custom documentation wasn't properly rendered
  custom_documentation/doc/endpoint/alerts/windows/windows_malware_alert.md
  custom_documentation/doc/endpoint/security/windows/windows_security_log_off.md
  custom_documentation/doc/endpoint/security/windows/windows_security_log_on.md
Labels: v8.16.0

#536 Optional File Event Hashes
  custom_documentation/doc/endpoint/file/linux/linux_file_create.md
  custom_documentation/doc/endpoint/file/linux/linux_file_rename.md
  custom_documentation/doc/endpoint/file/macos/macos_file_access.md
  custom_documentation/doc/endpoint/file/macos/macos_file_extended_attributes_delete.md
  custom_documentation/doc/endpoint/file/macos/macos_file_modification.md
  custom_documentation/doc/endpoint/file/macos/macos_file_rename.md
  custom_documentation/doc/endpoint/file/windows/windows_file_create.md
  custom_documentation/doc/endpoint/file/windows/windows_file_modification.md
  custom_documentation/doc/endpoint/file/windows/windows_file_open.md
  custom_documentation/doc/endpoint/file/windows/windows_file_overwrite.md
  custom_documentation/doc/endpoint/file/windows/windows_file_rename.md
  custom_documentation/src/endpoint/data_stream/file/linux/linux_file_create.yaml
  custom_documentation/src/endpoint/data_stream/file/linux/linux_file_rename.yaml
  custom_documentation/src/endpoint/data_stream/file/macos/macos_file_access.yaml
  custom_documentation/src/endpoint/data_stream/file/macos/macos_file_extended_attributes_delete.yaml
  custom_documentation/src/endpoint/data_stream/file/macos/macos_file_modification.yaml
  custom_documentation/src/endpoint/data_stream/file/macos/macos_file_rename.yaml
  custom_documentation/src/endpoint/data_stream/file/windows/windows_file_create.yaml
  custom_documentation/src/endpoint/data_stream/file/windows/windows_file_modification.yaml
  custom_documentation/src/endpoint/data_stream/file/windows/windows_file_open.yaml
  custom_documentation/src/endpoint/data_stream/file/windows/windows_file_overwrite.yaml
  custom_documentation/src/endpoint/data_stream/file/windows/windows_file_rename.yaml
Labels: documentation, v8.16.0

#538 Secondary Malware Signature Fields
  custom_documentation/doc/endpoint/alerts/linux/linux_malware_alert.md
  custom_documentation/doc/endpoint/alerts/macos/macos_malware_alert.md
  custom_documentation/src/endpoint/data_stream/alerts/linux/linux_malware_alert.yaml
  custom_documentation/src/endpoint/data_stream/alerts/macos/macos_malware_alert.yaml
  custom_schemas/custom_malware_signature.yml
  package/endpoint/data_stream/api/fields/fields.yml
  schemas/v1/api/api.yaml
Labels: bug, v8.16.0, v8.15.2

#540 Add dns.resolved_ip to Windows custom docs to address recent regression.
  custom_documentation/doc/endpoint/network/windows/windows_network_dns_lookup_result.md
  custom_documentation/src/endpoint/data_stream/network/windows/windows_network_dns_lookup_result.yaml
  package/endpoint/data_stream/network/sample_event.json
Labels: v8.16.0

#539 [8.15] [BACKPORT] Secondary Malware Signature Fields (#538)
  custom_documentation/doc/endpoint/alerts/linux/linux_malware_alert.md
  custom_documentation/doc/endpoint/alerts/macos/macos_malware_alert.md
  custom_documentation/src/endpoint/data_stream/alerts/linux/linux_malware_alert.yaml
  custom_documentation/src/endpoint/data_stream/alerts/macos/macos_malware_alert.yaml
  custom_schemas/custom_malware_signature.yml
  package/endpoint/data_stream/api/fields/fields.yml
  schemas/v1/api/api.yaml
Labels: bug, backport, v8.15.2

#527 WMI (WMI-Activity ETW Provider) API Event (production)
  custom_schemas/custom_api.yml
  package/endpoint/data_stream/api/fields/fields.yml
  package/endpoint/data_stream/api/sample_event.json
  schemas/v1/api/api.yaml
Labels: v8.16.0

#547 Add winlog.event_data.PrivilegeList to security events
  custom_schemas/custom_winlog.yml
  custom_subsets/elastic_endpoint/security/security.yaml
  package/endpoint/data_stream/security/fields/fields.yml
  package/endpoint/data_stream/security/sample_event.json
  package/endpoint/docs/README.md
  schemas/v1/security/security.yaml
Labels: v8.16.0

#548 Update custom documentation for winlog.event_data.PrivilegeList
  custom_documentation/doc/endpoint/security/windows/windows_security_log_on.md
  custom_documentation/src/endpoint/data_stream/security/windows/windows_security_log_on.yaml
Labels: v8.16.0

#544 Consolidate fork,exec,exit for macOS
  custom_documentation/doc/endpoint/process/macos/macos_process_exec.md
  custom_documentation/doc/endpoint/process/macos/macos_process_fork.md
  custom_documentation/doc/endpoint/process/macos/macos_process_fork_exec_exit.md
  custom_documentation/src/endpoint/data_stream/process/macos/macos_process_exec.yaml
  custom_documentation/src/endpoint/data_stream/process/macos/macos_process_exit.yaml
  custom_documentation/src/endpoint/data_stream/process/macos/macos_process_fork_exec_exit.yaml
Labels: v8.16.0

#549 Add Windows process aggregation
  custom_documentation/doc/endpoint/process/windows/windows_process_create_and_exit.md
  custom_documentation/doc/endpoint/process/windows/windows_process_exit.md
  custom_documentation/src/endpoint/data_stream/process/windows/windows_process_create_and_exit.yaml
  custom_documentation/src/endpoint/data_stream/process/windows/windows_process_exit.yaml
Labels: v8.16.0
